version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    target-branch: "develop"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      # Ignore patch updates for testing packages
      - dependency-name: "pytest*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "black"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "flake8*"
        update-types: ["version-update:semver-patch"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    target-branch: "develop"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Pre-commit hooks
  - package-ecosystem: "pip"
    directory: "/.pre-commit-config.yaml"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    target-branch: "develop"
    labels:
      - "dependencies"
      - "pre-commit"
    commit-message:
      prefix: "build"
      include: "scope"
