version: '1'

ignore:
  - .git
  - .env
  - venv
  - __pycache__
  - .pytest_cache
  - .coverage
  - .mypy_cache

rule_settings:
  enable:
    - default
    - python
    - async
    - typing
    - performance
  
  python_version: '3.11'

metrics:
  quality_threshold: 80.0

clone_detection:
  min_lines: 3
  min_duplicates: 2
  identical_clones_only: false 