PREFIX : <./chatbot#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?instance ?type ?label ?comment
WHERE {
    ?instance a ?type ;
             rdfs:label ?label .
    FILTER(?type != owl:Class && ?type != owl:ObjectProperty && ?type != owl:DatatypeProperty)
    OPTIONAL { ?instance rdfs:comment ?comment }
}
ORDER BY ?type ?label 