PREFIX : <./chatbot#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX guidance: <./guidance#>

SELECT ?interp ?label ?source ?target
WHERE {
    ?interp rdf:type guidance:Interpretation ;
            rdfs:label ?label .
    OPTIONAL { ?interp guidance:sourceContext ?source }
    OPTIONAL { ?interp guidance:targetContext ?target }
}
