name: Development Validation

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install flake8 black mypy

      - name: Code style check
        run: |
          black --check teams_bot
          flake8 teams_bot --max-line-length=100
        continue-on-error: true  # Development phase: informative only

      - name: Type check
        run: |
          mypy teams_bot --ignore-missing-imports
        continue-on-error: true  # Development phase: informative only

      - name: Validate ontology
        run: |
          python teams_bot/validate_deployment.py
        continue-on-error: true  # Development phase: informative only

      # Tests will be added here once we have them
      # - name: Run tests
      #   run: pytest teams_bot/tests/
